#!/usr/bin/env bash

profile="default"
format="table"

if [ ! -z $1 ];then
   profile=$1
fi

if [ ! -z $2 ];then
   format=$2
fi

aws ec2 describe-volumes --filter "Name=status,Values=in-use" --query 'Volumes[*].{ID:VolumeId,Size:Size,Type:VolumeType,AvailabilityZone:AvailabilityZone,Encrypted:Encrypted,Name:Tags[?Key==`Name`]|[0].Value,IOPS:Iops}' --profile=${profile} --output=${format}
