#!/usr/bin/env bash

profile="default"
format="table"

if [ ! -z $1 ];then
   profile=$1
fi

if [ ! -z $2 ];then
   format=$2
fi

aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId,InstanceType,PublicIpAddress,PrivateIpAddress,Tags[?Key==`Name`]| [0].Value,State.Name]' --output ${format} --profile=${profile}
