#!/usr/bin/env bash
###################################################################
# Script to create fast restore snapshots for snapshots
#
# VN v1.0
# 20200928
#
# Important Notes: 
#   - Snapshot has to be in completed state
###################################################################

function Usage(){
	echo -e "\n$0 ENV snap_filter availability_zone\n"
        echo -e "Example to create fast restore snapshot for UK webdb snapshot in az-a:\n\t $0 uk webdb a\n"
}

########
# MAIN
########

if [ ! -z "$1" ]; then
    ENV=$1
fi

if [ ! -z "$2" ]; then
        snapFilter=$2
fi

if [ ! -z "$3" ]; then
        azCode=$3
fi

if [ \( -z "$ENV" \) -o \( -z "$snapFilter" \) -o \( -z "$azCode" \) ] ;then
        Usage
        exit 2
fi

case "$ENV" in
    anz|au)
        PROFILE="default"
	REGION="ap-southeast-2" #Sydney
        ;;
    uk|UK)
        PROFILE="UK"
	REGION="eu-west-1" #Ireland
        ;;
    us|US)
        PROFILE="US"
	REGION="us-west-2" #Oregon
        ;;
    *)
        echo "ERR: $ENV not found"
        exit 3
        ;;
esac

ZONE="${REGION}${azCode}"

echo ""

echo -e "\nSearching for snapshot with filter ${snapFilter} ...\n"
#show most recent snapshot only
snapdetails=$(aws ec2 describe-snapshots --owner-ids self  --filters Name=status,Values=completed Name=tag:Name,Values=*${snapFilter}* --query 'sort_by(Snapshots, &StartTime)[-1].{SnapshotId:SnapshotId,VolumeId:VolumeId,State:State,Name:Tags[?Key==`Name`]|[0].Value}' --profile=${PROFILE} --output=text)

if [ ! -z "$snapdetails" ]; then
	echo -e "INFO: Snapshot detected\n\n${snapdetails}\n"
else
	echo "ERR: Snapshot cannot be found with given filter $snapFilter in $ENV. Bye!"
	exit 4
fi

snapArray=($snapdetails)

#debug
#for ((i=0; i<${#snapArray[@]}; ++i)); do     echo "snapdetails $i: ${snapArray[$i]}"; done

#extract snapshot details
snapName=${snapArray[0]}
snapId=${snapArray[1]}
snapStatus=${snapArray[2]}
snapVolid=${snapArray[3]}

#check if fast restore snapshot for given snapshot is already in progress
snapCheck=$(aws ec2 describe-fast-snapshot-restores --filters Name=availability-zone,Values=${ZONE} Name=state,Values=enabling,optimizing,enabled Name=snapshot-id,Values=${snapId} --profile=${PROFILE} --output=text)
##--query "Snapshots[*].{ID:SnapshotId,Time:StartTime}" 

if [ ! -z "$snapCheck" ]; then
	echo -e "WARN: Fast restore Snapshot is already in progress/completed for the snapshot ${snapName}:${snapId}. Aborting.\n\n${snapCheck}\n"
	exit 5
fi

echo "Creating EBS fast restore snapshot for the snapshot ${snapName}:${snapId}..."

aws ec2 enable-fast-snapshot-restores --availability-zones ${ZONE} --source-snapshot-ids ${snapId}
if [ $? == 0 ] ; then
	echo "INFO: Fast Restore Snapshot successfully started"
else
	echo "ERR: Fast Restore Snapshot creation failed"
fi
