#!/bin/bash

##########

function usage()
{
  echo -e "Usage: $0 -p AWS_PROFILE -r AWS_REGION -i AWS_SECRETID\nExample: $0 -p YOURAWSPROFILE -r ap-southeast-1 -i /secret/app/testuser1\n"
  exit 1
}

##########

#input processing
while getopts ":r:p:i:h" o
do
  case "${o}" in
    p)
      AWSPROFILE=${OPTARG}
      ;;
    r)
      AWSREGION=${OPTARG}
      ;;
    i)
      SECRETID=${OPTARG}
      ;;
    h|*)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

#instance-id is mandatory
if [ -z "${SECRETID}" ];then
    usage
fi

#default aws-profile and aws-region
if [ -z "${AWSPROFILE}" ];then
  AWSPROFILE="default"
fi

if [ -z "${AWSREGION}" ];then
  AWSREGION="ap-southeast-1"
fi

aws secretsmanager get-secret-value --secret-id ${SECRETID} --output=json --profile=${AWSPROFILE} --region=${AWSREGION}
